lolproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
# main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('champions/', views.champions_index, name='champions_index'),
    path('champions/<int:champion_id>/', views.champions_show, name='champions_show'),
    path('champions/create/', views.ChampionCreate.as_view(), name ='champions_create'),
    path('champions/<int:pk>/update/', views.ChampionUpdate.as_view(), name='champions_update'),
    path('champions/<int:pk>/delete/', views.ChampionDelete.as_view(), name='champions_delete'),
    path('user/<username>/', views.profile, name='profile'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('user/<username>/', views.profile, name='profile'),

    path('comments/', views.comments_index, name='comments_index'),
    path('comments/<int:comments_id>', views.comments_show, name='comments_show'),
    path('comments/<int:champion_id>/create/', views.comment_create, name='comment_create'),
    path('comments/<int:pk>/update/', views.CommentUpdate.as_view(), name='comments_update'),
    path('comments/<int:pk>/delete/', views.CommentDelete.as_view(), name='comments_delete')
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms.models import ModelForm


# Create your models here.

class Champion(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    lore = models.CharField(max_length=2000)

    abilityNameQ = models.CharField(max_length=100)
    abilityDescriptionQ = models.CharField(max_length=500)

    abilityNameW = models.CharField(max_length=100)
    abilityDescriptionW = models.CharField(max_length=500)

    abilityNameE = models.CharField(max_length=100)
    abilityDescriptionE = models.CharField(max_length=500)

    abilityNameR = models.CharField(max_length=100)
    abilityDescriptionR = models.CharField(max_length=500)
    
    def __str__(self):
        return self.name

class Comment(models.Model):
    text = models.CharField(max_length=2000)
    user = models.CharField(max_length=100)
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    champion = models.PositiveIntegerField()
    # champion = models.ForeignKey(Champion, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    champion = models.OneToOneField(Champion, on_delete=models.CASCADE)

main_app/views.py
from django.http.response import HttpResponseRedirect
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Champion, Comment, Favorite
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django import forms

# Create your views here.
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def champions_index(request):
    champions = Champion.objects.all()
    return render(request, 'champions/index.html', { 'champions': champions })

def champions_show(request, champion_id):
    champion = Champion.objects.get(id=champion_id)
    comments = Comment.objects.all()
    return render(request, 'champions/show.html', {'champion': champion, 'comment':comments})

def comments_index(request):
    comments = Comment.objects.all()
    return render(request, 'comments/inde.html', {'comments': comments})

def comments_show(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    return render(request, 'comments/show.html', {'comment': comment})

@login_required
def profile(request, username):
    user = User.objects.get(username=username)
    # champions = Champion.objects.filter(user=user)
    return render(request, 'profile.html', {'username': username})
    # return render(request, 'profile.html', {'username': username, 'champions': champions})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username = u, password = p)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/champions')
                else:
                    print('The account has been disabled.')
            else:
                print('The username and/or password is incorrect.')
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})
        
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/champions')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/login')
        else:
            return redirect('/signup')
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})
        

class ChampionCreate(CreateView):
    model = Champion
    fields = ['name', 'title', 'lore', 'abilityNameQ', 'abilityDescriptionQ', 'abilityNameW', 'abilityDescriptionW', 'abilityNameE', 'abilityDescriptionE', 'abilityNameR', 'abilityDescriptionR']
    success_url = '/champions'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/champions/' + str(self.object.pk))

class ChampionUpdate(UpdateView):
    model = Champion
    fields = ['name', 'title', 'lore', 'abilityNameQ', 'abilityDescriptionQ', 'abilityNameW', 'abilityDescriptionW', 'abilityNameE', 'abilityDescriptionE', 'abilityNameR', 'abilityDescriptionR']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return HttpResponseRedirect('/champions/' + str(self.object.pk))

@method_decorator(login_required, name='dispatch')
class ChampionDelete(DeleteView):
    model = Champion
    success_url ='/champions/'

# class CommentCreate(CreateView):
#     model = Comment
#     fields = ['text']

#     def form_valid(self, form):
#         self.object = form.save(commit=False)
#         self.object.user = self.request.user
#         self.object.save()
#         return HttpResponseRedirect('/champions/' + str(self.object.pk))
    

class CommentUpdate(UpdateView):
    model = Comment
    fields = ['text']
    success_url = '/champions/<id=champion.id>'

class CommentDelete(DeleteView):
    model = Comment
    fields = ['text']
    success_url = '/champions/<id=champion.id>'

# def comment_create(request, champion_id):
#         form = CommentCreate.as_view()
#         return render(request, 'main_app/comment_form.html', { 'form':form , 'champion_id':champion_id })


class CreateForm(forms.Form):
    model = Comment
    text = forms.CharField(max_length = 200)


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.champion_id = self.object.champion_id
        self.object.save()
        return HttpResponseRedirect('/champions/' + str(self.object.pk))

# def comment_create(request,champion_id):
#     context ={}
#     context['form']= CreateForm(champion_id)
#     context['champion_id']= champion_id
#     return render(request, "main_app/comment_form.html", context)

def comment_create(request,champion_id):
    if request.method == 'POST':
        fm = CreateForm(request.POST)
        if fm.is_valid():
            txt = fm.cleaned_data['text']
            reg = Comment(text=txt, champion=champion_id, user=request.user.id)
            reg.save()
            return HttpResponseRedirect('/champions/' + str(champion_id))
    else:
        fm = CreateForm()
    return render(request,'main_app/comment_form.html',{'form':fm})

main_app/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <title>About the catcollector...</title>
    </head>
    <body>
        <h1>About the catcollector...</h1>
        <hr />
        <p>Hire the catcollector!</p>
        <footer>All Rights Reserved, CatCollector 2021</footer>
    </body>
</html>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>LoL R Us</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.css">
  </head>
  <header>
    {% if user.is_authenticated %}
    <span> | </span>
    <span><a href="{% url 'profile' user.username %}">Hello, {{ user.username }}!</a></span>
    <span> | </span>
    <span><a href="{% url 'logout' %}">Logout</a></span>
    <span> | </span>
    {% else %}
    <span><a href="{% url 'login' %}">Login</a></span>
    <span> | </span>
    <span><a href="{% url 'signup' %}">SignUp</a></span>
    {% endif %}
    <a href="/champions">
        <h1>League of Legends Champions</h1>
    </a>
  </header>
  <hr />
  <body>
        {% block content %}
        {% endblock %}

      <footer>
        Some sort of footer 2021
      </footer>
  </body>
</html>

main_app/templates/champions/index.html
{% extends 'base.html' %}
{% load static %}
<!-- templates/champions/index.html -->

<!DOCTYPE html>
<html>
    <head>
        <title>LoL Champions</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <h1 class="champIndex">League of Legends' Champions</h1>
        <hr />
        {% block content %}
        <div>
        <a href="/champions/create">Add a New Champion!</a>
        <hr />
        
        {% for champion in champions %}
            <a href="/champions/{{champion.id}}">{{ champion.name }}</a>
            <p>Favorited By: {{champion.user.username}}</p>
            </a>
        <hr />
        {% endfor %}
        {% endblock %}
        </div>
        <footer>Whatever Footer 2021</footer>
    </body>
</html>

main_app/templates/champions/show.html
{% extends 'base.html' %}
{% block content %}
<div class="card-content">
    <h2> Name: {{ champion.name }}</h1>
    <p> Title: {{ champion.title }}</p>
    <p> Lore: {{ champion.lore}}</p>

    <p>Ability Q: {{ champion.abilityNameQ}}</p>
    <p>Ability Description: {{ champion.abilityDescriptionQ}}</p>

    <p>Ability W: {{ champion.abilityNameW}}</p>
    <p>Ability Description: {{ champion.abilityDescriptionW}}</p>

    <p>Ability E: {{ champion.abilityNameE}}</p>
    <p>Ability Description: {{ champion.abilityDescriptionE}}</p>

    <p>Ability R: {{ champion.abilityNameR}}</p>
    <p>Ability Description: {{ champion.abilityDescriptionR}}</p>
    Comments:
    <ol>{% for c in comment %}
    
        {% ifequal c.champion champion.id %}
            <li>{{ c }}</li>
        {% endifequal %}
    {% empty %}
        <div>Champion Has No Comments :(</div>
    {% endfor %}
    </ol>
    <a href="{% url 'champions_update' champion.id %}">Update Champion</a> |
    <a href="{% url 'champions_delete' champion.id %}">Delete This Champion</a>
    <a href="{% url 'comment_create' champion.id %}">Leave a Comment</a>
</div>
{% endblock %}

main_app/templates/comments/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Comment List</h1>

{% for comment in comments %}
    <div>
        <a href="{% url 'comments_show' comment.id %}">
            <div class="card-content">
                <p>{{ comment.text }}</p>
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/comments/show.html
{% extends 'base.html' %}
{% block content %}

<h1>Comment Details</h1>

<div>
    <div>
        <p>{{ comment.text }}</p>
        <p>Commented under </p>
        {% for champion in comment.champion_set.all %}
            <p>{{champion.name}}</p>
        {% empty %}
            <p>Nobody has this comment</p>
        {% endfor %}
    </div>
    <div>
        <a href="{% url 'comments_update' comment.id %}">Edit</a>
        <a href="{% url 'comments_delete' comment.id %}">Delete</a>
    </div>
</div>
{% endblock %}

main_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>LoL Project</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>
        <h1 class="projectTitle">League of Legends Project</h1>
        <hr />
        <div class="homepage">
            <a href="/champions">View All The League of Legends Champions!</a>
            <img src="https://s3-eu-central-1.amazonaws.com/www-staging.esports.com/WP%20Media%20Folder%20-%20esports-com//var/app/current/web/app/uploads/2021/02/Riot-Games-League-of-legends-beginners-guide-720x405.jpg"
        </div>
        <footer>Edison Fu 2021</footer>
    </body>
</html>

main_app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<form method="POST" action=".">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/main_app/champion_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Champion</h1>

    <p>Are you sure you want to delete this champion: {{ champion }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

main_app/templates/main_app/champion_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
    </form>
{% endblock %}

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Comment</h1>

    <h4>Are you sure you want to delete <strong>{{ comment }}</strong>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!">
        <a href="{% url 'comments_show' comment.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/main_app/comment_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
    </form>
{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{ username }}'s collection:</h1>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}